# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: training_jobs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='training_jobs.proto',
  package='dare',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13training_jobs.proto\x12\x04\x64\x61re\";\n\x13JobHeartbeatRequest\x12\x10\n\x08job_name\x18\x01 \x01(\t\x12\x12\n\nbatch_time\x18\x02 \x01(\x01\"$\n\x10JobFinishRequest\x12\x10\n\x08job_name\x18\x01 \x01(\t\"\x1f\n\x0eHeartbeatReply\x12\r\n\x05reply\x18\x01 \x01(\t\"\xce\x01\n\x0fJobStartRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0bnum_workers\x18\x04 \x01(\x05\x12\x1b\n\x13num_gpus_per_worker\x18\x05 \x01(\x05\x12\x0e\n\x06job_ip\x18\x06 \x01(\t\x12\x14\n\x0c\x64\x61taset_path\x18\x07 \x01(\t\x12\x18\n\x10steps_curr_epoch\x18\x08 \x01(\x03\x12\x1b\n\x13steps_future_epochs\x18\t \x01(\x03\"V\n\x0fNewEpochRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x10steps_curr_epoch\x18\x02 \x01(\x03\x12\x1b\n\x13steps_future_epochs\x18\x03 \x01(\x03\"\x1f\n\x0eJobStatusReply\x12\r\n\x05reply\x18\x01 \x01(\t2\x8b\x01\n\x0cJobHeartbeat\x12>\n\tHeartbeat\x12\x19.dare.JobHeartbeatRequest\x1a\x14.dare.HeartbeatReply\"\x00\x12;\n\tJobFinish\x12\x16.dare.JobFinishRequest\x1a\x14.dare.HeartbeatReply\"\x00\x32\xc5\x01\n\x10JobStatusHandler\x12\x39\n\x08JobStart\x12\x15.dare.JobStartRequest\x1a\x14.dare.JobStatusReply\"\x00\x12\x39\n\x08NewEpoch\x12\x15.dare.NewEpochRequest\x1a\x14.dare.JobStatusReply\"\x00\x12;\n\tJobFinish\x12\x16.dare.JobFinishRequest\x1a\x14.dare.JobStatusReply\"\x00\x62\x06proto3'
)




_JOBHEARTBEATREQUEST = _descriptor.Descriptor(
  name='JobHeartbeatRequest',
  full_name='dare.JobHeartbeatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_name', full_name='dare.JobHeartbeatRequest.job_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_time', full_name='dare.JobHeartbeatRequest.batch_time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=88,
)


_JOBFINISHREQUEST = _descriptor.Descriptor(
  name='JobFinishRequest',
  full_name='dare.JobFinishRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_name', full_name='dare.JobFinishRequest.job_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=126,
)


_HEARTBEATREPLY = _descriptor.Descriptor(
  name='HeartbeatReply',
  full_name='dare.HeartbeatReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='dare.HeartbeatReply.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=159,
)


_JOBSTARTREQUEST = _descriptor.Descriptor(
  name='JobStartRequest',
  full_name='dare.JobStartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='dare.JobStartRequest.model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataset', full_name='dare.JobStartRequest.dataset', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='dare.JobStartRequest.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_workers', full_name='dare.JobStartRequest.num_workers', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_gpus_per_worker', full_name='dare.JobStartRequest.num_gpus_per_worker', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='job_ip', full_name='dare.JobStartRequest.job_ip', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataset_path', full_name='dare.JobStartRequest.dataset_path', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steps_curr_epoch', full_name='dare.JobStartRequest.steps_curr_epoch', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steps_future_epochs', full_name='dare.JobStartRequest.steps_future_epochs', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=368,
)


_NEWEPOCHREQUEST = _descriptor.Descriptor(
  name='NewEpochRequest',
  full_name='dare.NewEpochRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='dare.NewEpochRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steps_curr_epoch', full_name='dare.NewEpochRequest.steps_curr_epoch', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steps_future_epochs', full_name='dare.NewEpochRequest.steps_future_epochs', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=456,
)


_JOBSTATUSREPLY = _descriptor.Descriptor(
  name='JobStatusReply',
  full_name='dare.JobStatusReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='dare.JobStatusReply.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=489,
)

DESCRIPTOR.message_types_by_name['JobHeartbeatRequest'] = _JOBHEARTBEATREQUEST
DESCRIPTOR.message_types_by_name['JobFinishRequest'] = _JOBFINISHREQUEST
DESCRIPTOR.message_types_by_name['HeartbeatReply'] = _HEARTBEATREPLY
DESCRIPTOR.message_types_by_name['JobStartRequest'] = _JOBSTARTREQUEST
DESCRIPTOR.message_types_by_name['NewEpochRequest'] = _NEWEPOCHREQUEST
DESCRIPTOR.message_types_by_name['JobStatusReply'] = _JOBSTATUSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JobHeartbeatRequest = _reflection.GeneratedProtocolMessageType('JobHeartbeatRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOBHEARTBEATREQUEST,
  '__module__' : 'training_jobs_pb2'
  # @@protoc_insertion_point(class_scope:dare.JobHeartbeatRequest)
  })
_sym_db.RegisterMessage(JobHeartbeatRequest)

JobFinishRequest = _reflection.GeneratedProtocolMessageType('JobFinishRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOBFINISHREQUEST,
  '__module__' : 'training_jobs_pb2'
  # @@protoc_insertion_point(class_scope:dare.JobFinishRequest)
  })
_sym_db.RegisterMessage(JobFinishRequest)

HeartbeatReply = _reflection.GeneratedProtocolMessageType('HeartbeatReply', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATREPLY,
  '__module__' : 'training_jobs_pb2'
  # @@protoc_insertion_point(class_scope:dare.HeartbeatReply)
  })
_sym_db.RegisterMessage(HeartbeatReply)

JobStartRequest = _reflection.GeneratedProtocolMessageType('JobStartRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOBSTARTREQUEST,
  '__module__' : 'training_jobs_pb2'
  # @@protoc_insertion_point(class_scope:dare.JobStartRequest)
  })
_sym_db.RegisterMessage(JobStartRequest)

NewEpochRequest = _reflection.GeneratedProtocolMessageType('NewEpochRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEWEPOCHREQUEST,
  '__module__' : 'training_jobs_pb2'
  # @@protoc_insertion_point(class_scope:dare.NewEpochRequest)
  })
_sym_db.RegisterMessage(NewEpochRequest)

JobStatusReply = _reflection.GeneratedProtocolMessageType('JobStatusReply', (_message.Message,), {
  'DESCRIPTOR' : _JOBSTATUSREPLY,
  '__module__' : 'training_jobs_pb2'
  # @@protoc_insertion_point(class_scope:dare.JobStatusReply)
  })
_sym_db.RegisterMessage(JobStatusReply)



_JOBHEARTBEAT = _descriptor.ServiceDescriptor(
  name='JobHeartbeat',
  full_name='dare.JobHeartbeat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=492,
  serialized_end=631,
  methods=[
  _descriptor.MethodDescriptor(
    name='Heartbeat',
    full_name='dare.JobHeartbeat.Heartbeat',
    index=0,
    containing_service=None,
    input_type=_JOBHEARTBEATREQUEST,
    output_type=_HEARTBEATREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='JobFinish',
    full_name='dare.JobHeartbeat.JobFinish',
    index=1,
    containing_service=None,
    input_type=_JOBFINISHREQUEST,
    output_type=_HEARTBEATREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_JOBHEARTBEAT)

DESCRIPTOR.services_by_name['JobHeartbeat'] = _JOBHEARTBEAT


_JOBSTATUSHANDLER = _descriptor.ServiceDescriptor(
  name='JobStatusHandler',
  full_name='dare.JobStatusHandler',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=634,
  serialized_end=831,
  methods=[
  _descriptor.MethodDescriptor(
    name='JobStart',
    full_name='dare.JobStatusHandler.JobStart',
    index=0,
    containing_service=None,
    input_type=_JOBSTARTREQUEST,
    output_type=_JOBSTATUSREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='NewEpoch',
    full_name='dare.JobStatusHandler.NewEpoch',
    index=1,
    containing_service=None,
    input_type=_NEWEPOCHREQUEST,
    output_type=_JOBSTATUSREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='JobFinish',
    full_name='dare.JobStatusHandler.JobFinish',
    index=2,
    containing_service=None,
    input_type=_JOBFINISHREQUEST,
    output_type=_JOBSTATUSREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_JOBSTATUSHANDLER)

DESCRIPTOR.services_by_name['JobStatusHandler'] = _JOBSTATUSHANDLER

# @@protoc_insertion_point(module_scope)
